#!/usr/bin/env ruby

Dir["./lib/*.rb"].each {|file| require file }
PlayAnalyser.new(downloader: XmlDownloader, analysis_engine: AnalysisEngine).analyse_play("http://www.ibiblio.org/xml/examples/shakespeare/macbeth.xml")
